[package]
name = "empire"
version = "0.1.0"
authors = ["Pepeye <gaofolaju@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "0.7.18"

chrono = "0.4"
uuid = { version = "0.7.2", features = ["v4"] }
env_logger = "0.6.0"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "*"